name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    permissions:
      contents: write # Needed to update release with binary assets
      packages: write # Needed for GHCR image push
      id-token: write # needed for the Vault authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries
        run: make multi-arch-build

      - name: Compute checksum for each binary
        run: |
          arch=("amd64" "arm64" "arm")
          cd dist/artifacts
          for a in "${arch[@]}"; do
            sha256sum kine-"${a}" > sha256sum-"${a}".txt
          done
          
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2.2.1 # https://github.com/softprops/action-gh-release/issues/587
        with:
          files: |
            dist/artifacts/kine-*
            dist/artifacts/*.txt
